// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbTGrj6B4vIuO5EGcwYxdleOKIweujU0',
    appId: '1:76840675232:web:2a12c11c50d84a1c2366c5',
    messagingSenderId: '76840675232',
    projectId: 'spend-less-2c352',
    authDomain: 'spend-less-2c352.firebaseapp.com',
    storageBucket: 'spend-less-2c352.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqD48-8xfKeTVs2_MaVhVht0TFmyGftUw',
    appId: '1:76840675232:android:1620d49362a0beb32366c5',
    messagingSenderId: '76840675232',
    projectId: 'spend-less-2c352',
    storageBucket: 'spend-less-2c352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL-2qMehPsQoJcifou2_OSxYBueWxhj6A',
    appId: '1:76840675232:ios:f3c29930a862a5f32366c5',
    messagingSenderId: '76840675232',
    projectId: 'spend-less-2c352',
    storageBucket: 'spend-less-2c352.appspot.com',
    iosClientId:
        '76840675232-7pvbp7d1bpqs9mf8005jdbgvikjj91bu.apps.googleusercontent.com',
    iosBundleId: 'com.sushant.expensetracker.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL-2qMehPsQoJcifou2_OSxYBueWxhj6A',
    appId: '1:76840675232:ios:f3c29930a862a5f32366c5',
    messagingSenderId: '76840675232',
    projectId: 'spend-less-2c352',
    storageBucket: 'spend-less-2c352.appspot.com',
    iosClientId:
        '76840675232-7pvbp7d1bpqs9mf8005jdbgvikjj91bu.apps.googleusercontent.com',
    iosBundleId: 'com.sushant.expensetracker.expensetracker',
  );
}
